CREATE TABLE cities
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_cities PRIMARY KEY (id)
);

CREATE TABLE stops
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    url      VARCHAR(256)                            NOT NULL,
    address  VARCHAR(32)                             NOT NULL,
    count    INTEGER                                 NOT NULL,
    velocity INTEGER                                 NOT NULL,
    load     INTEGER                                 NOT NULL,
    city_id  BIGINT                                  NOT NULL,
    lat      DECIMAL(9, 6),
    lng      DECIMAL(9, 6),
    CONSTRAINT pk_stops PRIMARY KEY (id)
);

CREATE TABLE stops_history
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    city_id  BIGINT                                  NOT NULL,
    address  VARCHAR(32)                             NOT NULL,
    count    INTEGER                                 NOT NULL,
    velocity INTEGER                                 NOT NULL,
    load     INTEGER                                 NOT NULL,
    datetime TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_stops_history PRIMARY KEY (id)
);

ALTER TABLE stops_history
    ADD CONSTRAINT FK_STOPS_HISTORY_ON_CITY FOREIGN KEY (city_id) REFERENCES cities (id);

ALTER TABLE stops
    ADD CONSTRAINT FK_STOPS_ON_CITY FOREIGN KEY (city_id) REFERENCES cities (id);