version: "3.8"

services:

  postgres:
    container_name: postgres
    image: postgres:17.5
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=stops
      - POSTGRES_PORT=5432

