jwt.secret=VGhpcy1pc0Etc2VjcmV0S2V5LXlvdS1zaG91bGQtdXNlIQ==
jwt.reset-token-expiration=300000

# ===============================
# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/stops
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA/HIBERNATE CONFIGURATION
# ===============================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# ===============================
# JACKSON (JSON) CONFIGURATION
# ===============================
# spring.jackson.property-naming-strategy=SNAKE_CASE
spring.jackson.serialization.indent-output=true
spring.jackson.default-property-inclusion=NON_NULL

# ===============================
# SERVER CONFIGURATION
# ===============================
server.port=8080
#server.servlet.context-path=/api
spring.application.name=flowdetect

# ===============================
# ML FORECAST SERVICE CONFIGURATION
# ===============================
ml.forecast.service.url=http://localhost:8082
ml.passenger-flow.service.url=http://passenger-flow-predicted:8083

# ===============================
# FEIGN CLIENT CONFIGURATION
# ===============================
feign.client.config.default.connectTimeout=300000
feign.client.config.default.readTimeout=600000
feign.client.config.default.loggerLevel=full
feign.compression.response.enabled=true
feign.compression.request.enabled=true


# ИЛИ точечно для конкретного клиента (рекомендуется)
feign.client.config.flow-prediction-ml.connectTimeout=300000
feign.client.config.flow-prediction-ml.readTimeout=300000

# ===============================
# SPRING CLOUD FEIGN CONFIGURATION
# ===============================
spring.cloud.openfeign.enabled=true
spring.cloud.openfeign.httpclient.hc5.enabled=true
spring.cloud.openfeign.compression.request.enabled=true
spring.cloud.openfeign.compression.response.enabled=true

# ===============================
# LOGGING CONFIGURATION
# ===============================
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
#logging.level.org.hibernate.SQL=ERROR
logging.level.ru.slivkiai.flowdetect.client=DEBUG
logging.level.feign=DEBUG
# ??? ?????? SQL
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Docker Compose
spring.docker.compose.enabled=false

# SpringDoc
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.operationsSorter=alpha

# Security
springdoc.show-actuator=true
springdoc.cache.disabled=true
springdoc.swagger-ui.enabled=true
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

# Migrat
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true


# === Mail ===
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=software.security.work@gmail.com
spring.mail.password=eukh iuzx kmgs aibc

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.properties.mail.smtp.connectiontimeout=50000
spring.mail.properties.mail.smtp.timeout=50000
spring.mail.properties.mail.smtp.writetimeout=50000