CREATE TABLE cities
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    lat      DECIMAL(9, 6)                       NOT NULL,
    lng      DECIMAL(9, 6)                       NOT NULL,
    CONSTRAINT pk_cities PRIMARY KEY (id)
);

CREATE TABLE stops
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    url      VARCHAR(256)                            NULL,
    address  VARCHAR(32)                             NOT NULL,
    count    INTEGER                                 NOT NULL,
    velocity INTEGER                                 NOT NULL,
    load     INTEGER                                 NOT NULL,
    city_id  BIGINT                                  NOT NULL,
    lat      DECIMAL(9, 6)                           NOT NULL,
    lng      DECIMAL(9, 6)                           NOT NULL,
    CONSTRAINT pk_stops PRIMARY KEY (id)
);

CREATE TABLE stops_history
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    city_id  BIGINT                                  NOT NULL,
    address  VARCHAR(32)                             NOT NULL,
    count    INTEGER                                 NOT NULL,
    velocity INTEGER                                 NOT NULL,
    load     INTEGER                                 NOT NULL,
    datetime TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_stops_history PRIMARY KEY (id)
);

ALTER TABLE stops_history
    ADD CONSTRAINT FK_STOPS_HISTORY_ON_CITY FOREIGN KEY (city_id) REFERENCES cities (id);

ALTER TABLE stops
    ADD CONSTRAINT FK_STOPS_ON_CITY FOREIGN KEY (city_id) REFERENCES cities (id);

-- Добавляем таблицы для погоды и событий
CREATE TABLE weather_data (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                              city_id BIGINT NOT NULL,
                              datetime TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                              temperature DECIMAL(4,1),
                              precipitation DECIMAL(4,1),
                              weather_code INTEGER,
                              CONSTRAINT pk_weather_data PRIMARY KEY (id)
);

CREATE TABLE events (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                        city_id BIGINT NOT NULL,
                        event_date DATE NOT NULL,
                        is_holiday BOOLEAN DEFAULT FALSE,
                        has_special_event BOOLEAN DEFAULT FALSE,
                        event_type VARCHAR(50),
                        CONSTRAINT pk_events PRIMARY KEY (id)
);

ALTER TABLE weather_data
    ADD CONSTRAINT FK_WEATHER_DATA_ON_CITY FOREIGN KEY (city_id) REFERENCES cities (id);

ALTER TABLE events
    ADD CONSTRAINT FK_EVENTS_ON_CITY FOREIGN KEY (city_id) REFERENCES cities (id);

-- Создаем индексы для быстрого поиска
CREATE INDEX idx_weather_city_datetime ON weather_data(city_id, datetime);
CREATE INDEX idx_events_city_date ON events(city_id, event_date);