-- Создаем ENUM для типов транспорта
CREATE TYPE transport_type AS ENUM ('BUS', 'TROLLEYBUS', 'TRAM', 'MINIBUS', 'METRO', 'TRAIN');

-- Таблица маршрутов
CREATE TABLE routes
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    number              VARCHAR(32)                             NOT NULL,
    name                VARCHAR(128),
    transport_type      transport_type                          NOT NULL,
    is_active           BOOLEAN                                 NOT NULL DEFAULT TRUE,
    city_id             BIGINT                                  NOT NULL,
    direction_a_name    VARCHAR(128),
    direction_b_name    VARCHAR(128),
    interval_minutes    INTEGER,
    operating_hours     VARCHAR(100),
    created_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_routes PRIMARY KEY (id)
);

-- Таблица связи маршрутов и остановок (с порядком)
CREATE TABLE route_stops
(
    route_id            BIGINT                                  NOT NULL,
    stop_id             BIGINT                                  NOT NULL,
    order_in_route      INTEGER                                 NOT NULL,
    direction           VARCHAR(1), -- 'A' или 'B' для двунаправленных маршрутов
    travel_time_to_next INTEGER, -- время до следующей остановки в минутах
    is_active           BOOLEAN                                 NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_route_stops PRIMARY KEY (route_id, stop_id)
);

-- Добавляем внешние ключи для таблиц маршрутов
ALTER TABLE routes
    ADD CONSTRAINT FK_ROUTES_ON_CITY FOREIGN KEY (city_id) REFERENCES cities (id);

ALTER TABLE route_stops
    ADD CONSTRAINT FK_ROUTE_STOPS_ON_ROUTE FOREIGN KEY (route_id) REFERENCES routes (id) ON DELETE CASCADE;

ALTER TABLE route_stops
    ADD CONSTRAINT FK_ROUTE_STOPS_ON_STOP FOREIGN KEY (stop_id) REFERENCES stops (id) ON DELETE CASCADE;

-- Создаем индексы для быстрого поиска
CREATE INDEX idx_routes_city ON routes(city_id);
CREATE INDEX idx_routes_city_type ON routes(city_id, transport_type);
CREATE INDEX idx_routes_city_active ON routes(city_id, is_active);
CREATE INDEX idx_routes_number ON routes(number);

CREATE INDEX idx_route_stops_route ON route_stops(route_id);
CREATE INDEX idx_route_stops_stop ON route_stops(stop_id);
CREATE INDEX idx_route_stops_order ON route_stops(route_id, direction, order_in_route);
CREATE INDEX idx_route_stops_route_direction ON route_stops(route_id, direction);

-- Добавляем ограничение уникальности для номера маршрута в рамках города и типа транспорта
ALTER TABLE routes
    ADD CONSTRAINT uc_routes_city_type_number UNIQUE (city_id, transport_type, number);

-- Триггер для обновления updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
    RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_routes_updated_at
    BEFORE UPDATE ON routes
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Вспомогательные индексы для оптимизации запросов
CREATE INDEX idx_route_stops_active ON route_stops(is_active);
CREATE INDEX idx_routes_created_at ON routes(created_at);

-- Создаем представление для удобного получения маршрутов с остановками
CREATE OR REPLACE VIEW route_details AS
SELECT
    r.id AS route_id,
    r.number AS route_number,
    r.name AS route_name,
    r.transport_type,
    r.is_active AS route_active,
    r.city_id,
    c.name AS city_name,
    r.direction_a_name,
    r.direction_b_name,
    rs.stop_id,
    s.address AS stop_address,
    s.lat AS stop_lat,
    s.lng AS stop_lng,
    rs.order_in_route,
    rs.direction,
    rs.travel_time_to_next,
    rs.is_active AS stop_in_route_active,
    s.count AS current_count,
    s.velocity AS current_velocity,
    s.load AS current_load
FROM routes r
         JOIN cities c ON r.city_id = c.id
         JOIN route_stops rs ON r.id = rs.route_id
         JOIN stops s ON rs.stop_id = s.id
WHERE r.is_active = TRUE AND rs.is_active = TRUE
ORDER BY r.city_id, r.transport_type, r.number, rs.direction, rs.order_in_route;