[project]
name = "video-stream-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "loguru>=0.7.3",
    "opencv-python>=4.12.0.88",
    "pydantic>=2.11.7",
    "ultralytics>=8.3.176",
]
